name: Create Production Builds

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    type: build
    depends_on: fingerprint
    build_type: release
    platform: all

  submit:
    type: submit
    depends_on: build
    store: auto  # Submits to both stores